// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar/Sidebar.vue')['default']
    SidebarMenuItem: typeof import('./components/Sidebar/SidebarMenuItem.vue')['default']
    SidebarMobile: typeof import('./components/Sidebar/SidebarMobile.vue')['default']
  }
}
